In [1]:
import torch
import numpy as np

In [2]:
a = np.random.rand(3, 4, 5)
print(a)

[[[0.48104078 0.9886241  0.93516508 0.93869377 0.07478584]
  [0.50219388 0.56612147 0.41282936 0.11749506 0.41929409]
  [0.32964968 0.42700359 0.77993928 0.23675756 0.47030766]
  [0.1771731  0.31131502 0.52733955 0.76844008 0.69856172]]

 [[0.33902991 0.34740635 0.64285451 0.29661478 0.09219354]
  [0.2487494  0.56033561 0.97582079 0.77896357 0.48700471]
  [0.67911273 0.939073   0.56647162 0.22662938 0.25583513]
  [0.60281104 0.28136471 0.31120474 0.1819649  0.9983617 ]]

 [[0.51361245 0.37858306 0.04374042 0.39881547 0.20343122]
  [0.43983228 0.90790087 0.24748414 0.32083041 0.92237178]
  [0.154679   0.44092193 0.848892   0.84391914 0.14303847]
  [0.08604563 0.81619353 0.50808503 0.20671485 0.51555909]]]


In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.8284, 0.8046, 0.6510],
        [0.3212, 0.0335, 0.2827],
        [0.3672, 0.4957, 0.1651],
        [0.9344, 0.8643, 0.8721],
        [0.7822, 0.7900, 0.9538]])
